export enum TypeOption {
  line = 'line',
  area = 'area',
  bar = 'bar',
  histogram = 'histogram',
  pie = 'pie',
  donut = 'donut',
  radialBar = 'radialBar',
  scatter = 'scatter',
  bubble = 'bubble',
  heatmap = 'heatmap',
  treemap = 'treemap',
  boxPlot = 'boxPlot',
  candlestick = 'candlestick',
  radar = 'radar',
  polarArea = 'polarArea',
  rangeBar = 'rangeBar',
}
