import {
  ArrayOptionField,
  BoolOptionField,
  NumberOptionField,
  Options,
  SelectOptionField,
  TextOptionField,
} from '../optionModel';
import { ApexOptions } from 'apexcharts';

enum TitleAlign {
  left = 'left',
  center = 'center',
  right = 'right',
}

const apexOptionsModel: Options<ApexOptions> = {
  annotations: {
    position: new TextOptionField(),
    yaxis: new ArrayOptionField(),
    xaxis: new ArrayOptionField(),
    points: new ArrayOptionField(),
    texts: new ArrayOptionField(),
    images: new ArrayOptionField(),
  },
  chart: {
    width: null,
    height: null,
    type: null,
    foreColor: undefined,
    fontFamily: undefined,
    background: undefined,
    offsetX: undefined,
    offsetY: undefined,
    dropShadow: undefined,
    events: undefined,
    brush: undefined,
    id: undefined,
    group: undefined,
    locales: undefined,
    defaultLocale: undefined,
    parentHeightOffset: undefined,
    redrawOnParentResize: undefined,
    redrawOnWindowResize: undefined,
    sparkline: undefined,
    stacked: undefined,
    stackType: undefined,
    toolbar: undefined,
    zoom: undefined,
    selection: undefined,
    animations: undefined,
  },
  colors: new ArrayOptionField(),
  dataLabels: undefined,
  fill: undefined,
  forecastDataPoints: undefined,
  grid: undefined,
  labels: new ArrayOptionField(),
  legend: undefined,
  markers: undefined,
  noData: undefined,
  plotOptions: undefined,
  responsive: new ArrayOptionField(),
  series: null,
  states: undefined,
  stroke: undefined,
  subtitle: undefined,
  theme: undefined,
  title: {
    text: new TextOptionField(),
    align: new SelectOptionField(TitleAlign.left, TitleAlign),
    margin: new NumberOptionField(),
    offsetX: new NumberOptionField(),
    offsetY: new NumberOptionField(),
    floating: new BoolOptionField(),
    //...//
    style: {
      fontSize: new TextOptionField(),
      fontFamily: new TextOptionField(),
      fontWeight: new TextOptionField(),
      color: new TextOptionField(),
    },
  },
  tooltip: undefined,
  xaxis: undefined,
  yaxis: undefined,
};

export default apexOptionsModel;
